### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by ernosix** [petertodd/dust-b-gone#3]
I'm receiving a socket.timeout, came back with 22K+ dust txs, when I say yes to try and remove I get:
ubuntu@:~/dust-b-gone-master$ ./dust-b-gone.py --dry-run
Traceback (most recent call last):
  File "./dust-b-gone.py", line 47, in <module>
    dust_txouts = [unspent for unspent in proxy.listunspent(0) if unspent['amount'] <= args.dust]
  File "/usr/local/lib/python2.7/dist-packages/python_bitcoinlib-0.3.0-py2.7.egg/bitcoin/rpc.py", line 383, in listunspent
    r = self._call('listunspent', minconf, maxconf)
  File "/usr/local/lib/python2.7/dist-packages/python_bitcoinlib-0.3.0-py2.7.egg/bitcoin/rpc.py", line 144, in _call
    response = self._get_response()
  File "/usr/local/lib/python2.7/dist-packages/python_bitcoinlib-0.3.0-py2.7.egg/bitcoin/rpc.py", line 179, in _get_response
    http_response = self.__conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1038, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
socket.timeout: timed out

Bitcoind info, all system libaries are up to date: 
{
    "version" : 100200,
    "protocolversion" : 70002,
    "walletversion" : 60000,
    "balance" : ,
    "blocks" : 364335,
    "timeoffset" : 0,
    "connections" : 3,
    "proxy" : "",
    "difficulty" : 49402014931.22746277,
    "testnet" : false,
    "keypoololdest" : 1435806348,
    "keypoolsize" : 501,
    "paytxfee" : 0.00010000,
    "relayfee" : 0.00001000,
    "errors" : ""
}

Any suggestions greatly appreciated..

**Comment by petertodd** [comment]
Ah!

listunspent is taking so long that the proxy code is timing out on you. In dust-b-gone.py try changing:

    proxy = bitcoin.rpc.Proxy()

to

    proxy = bitcoin.rpc.Proxy(timeout=600)

and let me know if that works.

**Comment by ernosix** [comment]
Worked! Had to adjust it way up (4800), it took around 60 min, also had to bump up the size test.. Thanks a million Peter!

```
if sum_value_discarded > 0.5*COIN:
```

**Comment by petertodd** [comment]
Great!

Not sure what a good fix is here; listunspent() doesn't suppose pagination at all so Bitcoin Core needs to change itself to fix this.

If you can think of a documentation fix for the README, feel free to submit a pull-req.
